apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: c:\tools\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: grafana
    spec:
      volumes:
      - name: grafana-config-volume
        configMap:
          name: grafana-configmap
      containers:
      - image: grafana/grafana
        imagePullPolicy: Never
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - name: grafana-config-volume
          mountPath: "/etc/grafana/provisioning/datasources/datasource.yml"
          subPath: datasource.yml
      restartPolicy: Always
      serviceAccountName: ""
