kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-configmap
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
