apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: c:\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: metrics
  name: metrics
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: metrics
status:
  loadBalancer: {}
