apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: metrics
  name: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metrics
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: c:\tools\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: metrics
    spec:
      containers:
      - image: metrics:latest
        imagePullPolicy: Never
        name: metrics
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
