apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: c:\tools\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: prometheus
    spec:
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-configmap
      containers:
      - image: prom/prometheus:latest
        imagePullPolicy: Never
        name: prometheus
        ports:
        - containerPort: 9090
        resources: {}
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: "/etc/prometheus/prometheus.yml"
          subPath: prometheus.yml
      restartPolicy: Always
      serviceAccountName: ""
